### PR TITLE
Start mysqld_exporter after install

### PR DESCRIPTION
**Pull request by steinbrueckri**

### CODE REVIEW

**Comment by steinbrueckri** [comment]
@paulfantom can you have a look at this?
Br Richard

**Comment by rutger1140** [comment]
Could this be published as a new release? So we can use `ansible-galaxy` to maintain the version. 🙏

**Review by laurent-indermuehle — COMMENTED** [review]
systemd module doesn't have a "started" parameter. It's "state" you should use here.

Any reason why this task is in tasks/main.yml instead of a handler?

**Comment by steinbrueckri** [comment]
> systemd module doesn't have a "started" parameter. It's "state" you should use here.

Sorry will be fixed. 

> Any reason why this task is in tasks/main.yml instead of a handler?

Because it was like this before I touch it? 😅
I can move it to tasks/main if you whant.

**Comment by laurent-indermuehle** [comment]
@steinbrueckri Thanks for the reply! I done the changes in #40

**Pull request merged**
