### PR TITLE
Fix linter

### LINKED ISSUE #42: ansible-lint fails in CircleCI
The error from CircleCI is:

```
WARNING  Computed fully qualified role name of mysqld_exporter does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

WARNING  Loading custom .yamllint config file, this extends our internal yamllint config.
WARNING  Listing 2 violation(s) that are fatal
internal-error: the role 'ansible-mysqld_exporter' was not found in /home/circleci/project/molecule/alternative/roles:/home/circleci/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/circleci/.cache/ansible-lint/dda4ac/roles:/home/circleci/project/molecule/alternative
molecule/alternative/playbook.yml:6:7 [WARNING]: No inventory was parsed, only implicit localhost is available
```

I encounter that with my own role. I fixed the internal error by adding a dot after the command `ansible-lint`.
I'll try to fix that in a PR.

### PR DESCRIPTION
**Pull request by laurent-indermuehle**
This is an attempt to fix #42

### CODE REVIEW

**Comment by laurent-indermuehle** [comment]
Ok, now the "lint" step passes.
"molecule test -s default --destroy always" still fail, but the error regarding the missing role seems to be resolved.
The new error is: 

ERROR! couldn't resolve module/action 'community.docker.docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.

The issue may be explained here: https://github.com/ansible-community/molecule/issues/2755

Either we try to fix the molecule/<scenario>/collections.yml for 2.9 and 2.10. Or we could skip those versions to use ansible 3.1, 4.7 and 5.4 that are out for a while now.

But for people still on Ansible Automation Platform 1, the supported version is the 2.9...

**Comment by laurent-indermuehle** [comment]
Ok, now it works up utile this:

TASK [ansible-mysqld_exporter : Ensure mysqld_exporter is enabled on boot] *****
fatal: [bionic]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}
fatal: [buster]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}
fatal: [centos7]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}
fatal: [stretch]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}
fatal: [fedora]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}
fatal: [xenial]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: started Supported parameters include: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state, user"}

But I may have  fixed that in PR #40

**Comment by laurent-indermuehle** [comment]
Mergify now says: The new Mergify configuration is valid

I learned a lot about CircleCI and Github, thanks for that :)

Is there somebody at cloudalchemy who can find the time to review the PR please? @paulfantom maybe?
Many thanks for your roles! They're the first ones I use due to their great quality.

**Comment by SuperQ** [comment]
We have a bunch of things to fix in our CI right now. The changes are mostly done in our skeleton/automated updates. But we need to get things pushed out to all of the other projects.

I'm planning to do a bit of a hackathon with @paulfantom sometime soon to get things cleaned up.

**Comment by laurent-indermuehle** [comment]
Thanks for the reply @SuperQ 
I look forward to seeing the new CI setup then :)

**Comment by laurent-indermuehle** [comment]
Not stale

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
